---
title: "Developer Feedback Form"
labels: "dev feedback"

body:
  - type: markdown
    attributes:
      value: "# Developer Feedback Form"
  - type: markdown
    attributes:
      value: |
        Use this form to share feedback with the developers."
  - type: input
    id: discord-id
    attributes:
      label: "Discord Handle (optional)"
      description: "Enter your Discord username"
      placeholder: "@ratio13"
    validations:  
      required: false
  - type: input
    id: x-id
    attributes:
      label: "X Handle (optional)"
      description: "Enter your X (Twitter) username"
      placeholder: "@st8tik"
    validations:  
      required: false
  - type: input
    id: date-time
    attributes:
      label: "Please provide the DATE and TIME you experienced this issue."
      description: "Date [dd-mmm-yyyy] and Time [1300 UTC]"
      placeholder: "12-Jan-2025, 1300 UTC"
    validations:  
      required: true
  - type: markdown
    attributes:
      value: ---
  - type: dropdown
    id: severity
    attributes:
      label: "Select the product/project with these issues."
      options:
        - "DRep Sensemaking App"
        - "Other"
  - type: dropdown
    id: severity
    attributes:
      label: "Please rate the severity of this issue from the dropdown. Use your best judgement. If you are unsure please select unknown."
      options:
        - 1 - No Priority
        - 2 - Low Priority
        - 3 - Medium Priority
        - 4 - Med-High Priority
        - 5 - High Priority
        - 6 - Unknown
  - type: markdown
    attributes:
      value: ---    
  - type: textarea
    id: issue-description
    attributes:
      label: Please share any text feedback related to the issue being reported.
      description: Text description of issue(s).
      placeholder: Enter your text here.
    validations:  
      required: true  
  - type: markdown
    attributes:
      value: "### Drag and drop any files associated with your experience."
